version: '3'

services:
  vrc-stream:
    image: registry.sostoya.com/vrc-stream-server:0.0.1
    expose:
      - 1935
      - 80
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935

    networks:
      - proxy

    labels:
      - "traefik.enable=true"

      - "traefik.tcp.routers.rtmp_stream.entrypoints=rtmp"
      - "traefik.tcp.routers.rtmp_stream.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.rtmp_stream.service=rtmp_stream"
      - "traefik.tcp.services.rtmp_stream.loadbalancer.server.port=1935"

      - "traefik.http.routers.hls.entrypoints=web"
      - "traefik.http.routers.hls.rule=Host(`stream.sostoya.com`)"
      - "traefik.http.routers.hls.service=hls"
      - "traefik.http.services.hls.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
